# Generated by Django 5.2.4 on 2025-08-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_lab', '0001_initial'),
    ]

    operations = [

        
    ]
