# Generated by Django 5.2.4 on 2025-08-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_lab', '0002_auto_20250815_0931'),
    ]

    operations = [
    ]
